export const savAutoCareForm = {
  clientId: 3,
  businessTypeId: 3,
  corporateAddress: "Rajkot",
  ownerContact: "9856656",
  ownerEmail: "testing@gmail.com",
  ownerPhone: "5768678678879",
  state: "Gujrat",
  pabsGroupEmail: "testing@gmail.com",
  pabsPhone: "096-587-534576",
  service: "testing word",
  noOfLocations: 3,
  nameOfLocations: "testing word",
  noOfEntities: 4,
  noOfShops: 4,
  salesRep: "testing word",
  agreementDate: "05-06-2024",
  probableAcquisitionDate: "05-06-2024",
  dba: "testing word",
  clientWebsite: "testing word",
  shopManager: "testing word",
  poc1: "testing word",
  emailId: "testing word",
  contactInfo: "906-543-34535",
  cpa: "testing data",
  priorBookkeeperCpa: "updated testing word",
  itSupport: "testing word",
  timeZone: "testing word",
  weeklyCalls: 2,
  weeklyCallTime: "9:45",
  istTime: "2024",
  implementationManager: "testing word",
  implementationAnalyst: "testing word",
  operationsHead: "testing word",
  operationsManager: "testing word",
  operationsAccountHandler: "testing word",
  accountDetailsIsDisplay: true,
  legalStructureIsDisplay: true,
  cpaClientTeamIsDisplay: true,
  pabsAccountingTeamIsDisplay: true,
  phase1CommunicationIsDisplay: true,
  phase2SystemIsDisplay: true,
  phase3CashIsDisplay: true,
  phase4PayrollIsDisplay: true,
  phase5CompliancesIsDisplay: true,
  phase6ApPayableIsDisplay: true,
  phase7StatusIsDisplay: true,
  checkList: [
    {
      fieldName: "ABC",
      status: "Done",
      comments: "updated testing word",
      details: "ghfgh",
      actionsOfPabs: "gfhfg",
      actionsOfClient: "gfhgfh",
    },
    {
      fieldName: "XYZ",
      status: "working",
      comments: "updated testing word",
      details: "ghfgh",
      actionsOfPabs: "gfhfg",
      actionsOfClient: "updated testing word",
    },
  ],
  locationDetails: [
    {
      name: "ABC",
      details: "Done",
    },
    {
      name: "XYZR",
      details: "working",
    },
  ],
  salesTaxDetails: [
    {
      userId: 1,
      password: "Test@1234",
      status: "Done",
    },
  ],
  gmailAccountDetails: [
    {
      userId: 1,
      password: "Test@1234",
      status: "Done",
    },
  ],
  posDetails: [
    {
      POS: "CCC",
      serverName: "Test",
      personalKey: "123",
      userName: "ABCD",
      password: "Test@1234",
      status: "Done",
    },
  ],
  utilitiesDetails: [
    {
      location: 1,
      utilities: "APN",
      service: "system",
      account_customerNumber: "5454",
      user: "ABCD",
      password: "Test@1234",
      website: "testing word",
      status: "Done",
    },
  ],
  vendorDetails: [
    {
      location: 1,
      vendorName: "Test@1234",
      service: "working",
      vendorLoginLink: "testing word",
      vendorUserId: 1,
      vendorPassword: "Test@1234",
      status: "Done",
    },
  ],
  bankDetails: [
    {
      bankName: "testing word",
      type: "Test@1234",
      bankSiteLink: "working",
      companyId: 1,
      userId: 1,
      password: "Test@1234",
      status: "Done",
    },
  ],
  merchantDetails: [
    {
      merchantName: 1,
      link: "Test@1234",
      userId: 2,
      password: "testing word",
      accountId: 1,
      status: "Done",
    },
  ],
  payrollDetails: [
    {
      companyName: 1,
      link: "Test@1234",
      userId: 4,
      password: "testing word",
      passcode: "testing word",
      status: "Done",
    },
  ],
};
